### ISSUE TITLE
Lightbox Auswahloptionen fehlen

### ISSUE THREAD

**Issue by Nightwing0815** [cliffparnitzky/TinyMceLinkLightbox#2]
Hallo Cliff,

mir fiel gerade bei einer Seite nach dem Update auf 4.9.0 auf, das der Lightbox Auswahloptionen fehlen?!?
Hab gerade bei meinen anderen Installationen (4.8.8) geschaut: auch da ists weg.
Ich kann Dir leider nicht sagen, seit wann das so ist...

![2](https://user-images.githubusercontent.com/54181775/75082090-51e5ac00-5512-11ea-8350-aab95ec67f8c.PNG)

ToM

**Comment by cliffparnitzky** [comment]
Vielen Dank für den Hinweis. Nach einer Analyse habe ich die Ursache ermitteln können.

Siehe dazu https://github.com/cliffparnitzky/TinyMcePluginLoader/issues/14

**Comment by cliffparnitzky** [comment]
Gefixt mit https://github.com/cliffparnitzky/TinyMcePluginLoader/commit/c3f647c1558ff8f6d7a6928b9f1a4bfd890a10e3

Bitte mal via Composer/Contao Manager updaten, so dass https://packagist.org/packages/cliffparnitzky/tiny-mce-plugin-loader auf Version 2.1.10 aktualisiert wird.
